# Generated by Django 4.2.27 on 2026-01-29 07:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0002_topic_depth_alter_topic_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, help_text='Time spent: 0.1 to 12.0 hours', max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(12.0)])),
                ('learned_text', models.TextField(help_text='What was learned (50-500 characters)', validators=[django.core.validators.MinLengthValidator(50), django.core.validators.MaxLengthValidator(500)])),
                ('blockers_text', models.TextField(blank=True, help_text='Blocker details if any', null=True)),
                ('ai_status', models.CharField(choices=[('pending', 'Pending'), ('analyzed', 'Analyzed'), ('error', 'Error')], default='pending', max_length=20)),
                ('ai_decision', models.CharField(blank=True, choices=[('approve', 'Approve'), ('flag', 'Flag'), ('reject', 'Reject')], max_length=20, null=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_reasoning', models.TextField(blank=True, null=True)),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_override', models.BooleanField(default=False)),
                ('override_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('override_comment', models.TextField(blank=True, null=True)),
                ('override_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_entries', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entries', to='topics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'db_table': 'entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'date', 'topic'), name='unique_user_date_topic_entry'),
        ),
    ]
