# Generated by Django 4.2.27 on 2026-01-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_progress_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='True if the learner has finished this topic'),
        ),
    ]
