# Generated by Django 4.2.9 on 2026-02-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_entry_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='ai_reasoning',
        ),
        migrations.AddField(
            model_name='entry',
            name='ai_chain_of_thought',
            field=models.JSONField(default=dict, help_text='Multi-node AI reasoning logs'),
        ),
    ]
