# Generated by Django 4.2.27 on 2026-02-05 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0004_remove_entry_ai_reasoning_entry_ai_chain_of_thought'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalWisdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_type', models.CharField(choices=[('false_flag', 'AI flagged but should have approved'), ('false_approve', 'AI approved but should have flagged'), ('context_miss', 'AI missed important context')], max_length=20)),
                ('ai_original_decision', models.CharField(max_length=20)),
                ('admin_corrected_decision', models.CharField(max_length=20)),
                ('topic_name', models.CharField(max_length=100)),
                ('entry_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('entry_text_snippet', models.CharField(max_length=200)),
                ('admin_correction_reason', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wisdom_corrections', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wisdom_corrections', to='entries.entry')),
            ],
            options={
                'verbose_name': 'Global Wisdom Entry',
                'verbose_name_plural': 'Global Wisdom Pool',
                'db_table': 'global_wisdom',
                'ordering': ['-created_at'],
            },
        ),
    ]
