# Generated by Django 4.2.27 on 2026-02-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_learnertopicmastery'),
        ('entries', '0005_add_global_wisdom'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entry',
            name='unique_user_date_topic_entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='intent',
            field=models.CharField(choices=[('deep_learning', 'Deep Learning'), ('review', 'Review'), ('project_work', 'Project Work'), ('debugging', 'Debugging')], default='deep_learning', help_text='Activity type: deep_learning, review, project_work, debugging', max_length=20),
        ),
        migrations.AddField(
            model_name='entry',
            name='project_description',
            field=models.TextField(blank=True, help_text='One-time project description for context', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='project_name',
            field=models.CharField(blank=True, help_text='Project name for project_work/debugging entries', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Required for deep_learning/review. Optional for project_work/debugging.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='entries', to='topics.topic'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('topic__isnull', False)), fields=('user', 'date', 'topic'), name='unique_user_date_topic_entry'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('project_name__isnull', False)), fields=('user', 'date', 'project_name'), name='unique_user_date_project_entry'),
        ),
    ]
