# Generated by Django 4.2.9 on 2026-02-09 09:37

from django.db import migrations


def populate_projects(apps, schema_editor):
    """
    Create Project records from existing Entry.project_name values
    and link entries via the new project FK.
    """
    Entry = apps.get_model('entries', 'Entry')
    Project = apps.get_model('entries', 'Project')

    # Find all unique (user, project_name) combinations from active project entries
    project_entries = (
        Entry.objects.filter(
            is_active=True,
            intent__in=['project_work', 'debugging'],
            project_name__isnull=False,
        )
        .exclude(project_name='')
        .values_list('user_id', 'project_name')
        .distinct()
    )

    for user_id, project_name in project_entries:
        # Get description from the first entry that has one
        desc_entry = (
            Entry.objects.filter(
                user_id=user_id,
                project_name=project_name,
                is_active=True,
                project_description__isnull=False,
            )
            .exclude(project_description='')
            .order_by('created_at')
            .first()
        )
        description = desc_entry.project_description if desc_entry else ''

        # Check if any entry marks project as completed
        is_completed = Entry.objects.filter(
            user_id=user_id,
            project_name=project_name,
            is_active=True,
            is_completed=True,
        ).exists()

        # Create the Project
        project = Project.objects.create(
            user_id=user_id,
            name=project_name,
            description=description,
            is_completed=is_completed,
            is_active=True,
        )

        # Link all matching entries to this project
        Entry.objects.filter(
            user_id=user_id,
            project_name=project_name,
            is_active=True,
            intent__in=['project_work', 'debugging'],
        ).update(project_id=project.id)


def reverse_populate(apps, schema_editor):
    """Reverse: just unset all project FKs (Project records stay for safety)."""
    Entry = apps.get_model('entries', 'Entry')
    Entry.objects.filter(project__isnull=False).update(project=None)


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_add_project_model_and_fk'),
    ]

    operations = [
        migrations.RunPython(populate_projects, reverse_populate),
    ]
