# Generated by Django 4.2.9 on 2026-02-16 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_topic_domain_topic_language'),
        ('entries', '0009_merge_intent_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='project',
            field=models.ForeignKey(blank=True, help_text='FK to Project for sbu_tasks entries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='entries.project'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='project_name',
            field=models.CharField(blank=True, help_text='Project name for sbu_tasks entries', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Required for lnd_tasks. Optional for sbu_tasks.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='entries', to='topics.topic'),
        ),
    ]
