# Generated by Django 4.2.9 on 2026-02-25 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def auto_assign_existing_projects(apps, schema_editor):
    """
    Data migration: For each existing Project that has a `user` FK,
    create a ProjectAssignment row so the user retains access.
    Also set created_by = user (the original creator).
    """
    Project = apps.get_model('entries', 'Project')
    ProjectAssignment = apps.get_model('entries', 'ProjectAssignment')

    for project in Project.objects.all():
        if project.user_id:
            # Auto-assign the current user
            ProjectAssignment.objects.get_or_create(
                project=project,
                user_id=project.user_id,
            )
            # Set created_by to the original user (preserve history)
            project.created_by_id = project.user_id
            project.save(update_fields=['created_by_id'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0010_alter_entry_project_alter_entry_project_name_and_more'),
    ]

    operations = [
        # Step 1: Create ProjectAssignment model
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who made this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='entries.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Assignment',
                'verbose_name_plural': 'Project Assignments',
                'db_table': 'project_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('project', 'user')},
            },
        ),

        # Step 2: Add new fields BEFORE removing old ones
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created the project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Project end/deadline date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Project start date', null=True),
        ),

        # Step 3: Data migration — auto-assign existing projects to their users
        migrations.RunPython(
            auto_assign_existing_projects,
            reverse_code=migrations.RunPython.noop,
        ),

        # Step 4: Remove old constraint and user FK (AFTER data migration)
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_user_project_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
