# Generated by Django 4.2.9 on 2026-03-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_project_admin_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key_modules',
            field=models.JSONField(blank=True, default=list, help_text="List of key modules/features to build (e.g. ['Authentication', 'API', 'Dashboard'])"),
        ),
        migrations.AddField(
            model_name='project',
            name='out_of_scope',
            field=models.JSONField(blank=True, default=list, help_text="List of explicitly excluded features (e.g. ['Mobile app', 'ML features'])"),
        ),
        migrations.AddField(
            model_name='project',
            name='success_criteria',
            field=models.CharField(blank=True, default='', help_text="Performance targets or completion criteria (e.g. '<200ms API, 99.9% uptime')", max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, default='', help_text="Tech stack summary (e.g. 'React + Django + PostgreSQL + Docker')", max_length=200),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='role',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('fullstack', 'Full Stack'), ('devops', 'DevOps'), ('mobile', 'Mobile'), ('data', 'Data'), ('qa', 'QA'), ('design', 'Design'), ('lead', 'Lead'), ('general', 'General')], default='general', help_text="User's role on this project", max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
