# Generated by Django 4.2.9 on 2026-03-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_expand_project_role_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='feature_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', help_text='Status of the target module: in_progress or completed', max_length=20),
        ),
        migrations.AddField(
            model_name='entry',
            name='target_module',
            field=models.CharField(blank=True, help_text='Key module/feature the user worked on (for SBU entries)', max_length=200, null=True),
        ),
    ]
