# Generated by Django 4.2.9 on 2026-03-09 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_add_target_module_feature_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_backend',
            field=models.CharField(blank=True, default='', help_text="Backend tech (e.g. 'Django, Celery, Redis')", max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_cloud',
            field=models.CharField(blank=True, default='', help_text="Cloud/DevOps tech (e.g. 'AWS, Docker, GitHub Actions')", max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_database',
            field=models.CharField(blank=True, default='', help_text="Database tech (e.g. 'PostgreSQL, Redis')", max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_frontend',
            field=models.CharField(blank=True, default='', help_text="Frontend tech (e.g. 'React, Next.js, TailwindCSS')", max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, default='', help_text="Tech stack summary (e.g. 'React + Django + PostgreSQL + Docker') — legacy, use structured fields", max_length=200),
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('success_criteria', models.TextField(blank=True, default='', help_text="Comma-separated criteria (e.g. 'Token expiry, refresh logic')", max_length=500)),
                ('out_of_scope', models.JSONField(blank=True, default=list, help_text='Items excluded from this feature')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='entries.project')),
            ],
            options={
                'verbose_name': 'Project Feature',
                'verbose_name_plural': 'Project Features',
                'db_table': 'project_features',
                'ordering': ['project', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
