# Generated by Django 4.2.9 on 2026-03-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0015_add_project_feature_and_structured_tech'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['is_active', 'status'], name='idx_entry_active_status'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['is_active', 'ai_status'], name='idx_entry_active_ai_status'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['is_active', 'date'], name='idx_entry_active_date'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['is_active', 'topic_id'], name='idx_entry_active_topic'),
        ),
    ]
