# Generated by Django 4.2.9 on 2026-03-13 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0016_add_dashboard_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfeature',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User whose approved entry marked this feature complete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_features', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='reopened_by',
            field=models.ForeignKey(blank=True, help_text='User whose approved entry reopened this completed feature', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_features', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='started_by',
            field=models.ForeignKey(blank=True, help_text='User who first worked on this feature (first approved entry)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_features', to=settings.AUTH_USER_MODEL),
        ),
    ]
