# Generated by Django 4.2.9 on 2026-04-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0017_add_feature_audit_trail'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='git_evidence',
            field=models.JSONField(blank=True, default=dict, help_text='Git commit evidence: {commits_found, files_changed, lines_added, reasoning}'),
        ),
        migrations.AddField(
            model_name='entry',
            name='git_score_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Confidence adjustment from git analysis (-10 to +10)', max_digits=4),
        ),
        migrations.AddField(
            model_name='entry',
            name='git_validation_result',
            field=models.CharField(choices=[('pending', 'Pending'), ('match', 'Match'), ('partial', 'Partial Match'), ('no_match', 'No Match'), ('skipped', 'Skipped')], default='pending', help_text='Git commit validation result (advisory only)', max_length=20),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_non_coding',
            field=models.BooleanField(default=False, help_text='User self-reports this as non-coding work (design, meetings, docs)'),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, default='', help_text='GitHub repository URL (e.g. https://github.com/org/repo)', max_length=500),
        ),
    ]
