# Generated by Django 4.2.9 on 2026-01-27 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Must be @brainstation-23.com domain', max_length=255, unique=True)),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL', max_length=500, null=True, validators=[django.core.validators.RegexValidator(message='GitHub URL must be in format: https://github.com/username', regex='^https://github\\.com/[a-zA-Z0-9_-]+/?$')])),
                ('expertise_level', models.IntegerField(blank=True, help_text='Self-assessed skill level 1-10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('experience_years', models.DecimalField(blank=True, decimal_places=1, help_text='Years of professional experience', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text='Array of technologies/skills')),
                ('role', models.CharField(choices=[('learner', 'Learner'), ('admin', 'Admin')], default='learner', help_text='User role: learner or admin', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when user was soft deleted', null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'indexes': [models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(condition=models.Q(('is_active', True)), fields=['role'], name='idx_users_role'), models.Index(fields=['is_active'], name='users_is_acti_847b48_idx')],
            },
        ),
    ]
