# Generated by Django 4.2.9 on 2026-02-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_domain',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('devops', 'DevOps'), ('mobile', 'Mobile'), ('data', 'Data'), ('qa', 'QA'), ('general', 'General')], default='general', help_text="User's primary area of focus", max_length=20),
        ),
    ]
