# Generated by Django 4.2.9 on 2026-02-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_primary_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expertise_level',
        ),
    ]
