# Generated by Django 4.2.9 on 2026-03-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_expertise_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_domain',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Full Stack'), ('devops', 'DevOps'), ('devsecops', 'DevSecOps'), ('mobile', 'Mobile'), ('android', 'Android'), ('ios', 'iOS'), ('game', 'Game Developer'), ('game_server', 'Server Side Game Developer'), ('qa', 'QA'), ('test_automation', 'Test Automation'), ('data', 'Data Analyst'), ('data_engineer', 'Data Engineer'), ('ai', 'AI Engineer'), ('ai_data_scientist', 'AI and Data Scientist'), ('ml', 'Machine Learning'), ('mlops', 'MLOps'), ('bi', 'BI Analyst'), ('blockchain', 'Blockchain'), ('cyber_security', 'Cyber Security'), ('architect', 'Software Architect'), ('db_admin', 'PostgreSQL / DBA'), ('product_manager', 'Product Manager'), ('engineering_manager', 'Engineering Manager'), ('design', 'UX Design'), ('technical_writer', 'Technical Writer'), ('devrel', 'Developer Relations'), ('fundamentals', 'Computer Science / Fundamentals'), ('soft_skills', 'Soft Skills'), ('general', 'General')], default='general', help_text="User's primary area of focus", max_length=30),
        ),
    ]
