# Generated by Django 4.2.9 on 2026-04-24 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_expand_domain_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='', help_text='Department from ERP (e.g. Software Engineering)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, default='', help_text='Job position from ERP (e.g. Senior Software Engineer)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='ERP Employee ID (e.g. BS0733). Unique across all users.', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='erp_role',
            field=models.CharField(blank=True, default='', help_text='Organizational role from ERP (e.g. Project Manager, Developer)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.CharField(blank=True, default='', help_text='Area of expertise (self-editable)', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise_level',
            field=models.CharField(blank=True, default='', help_text='Expertise level: Beginner, Intermediate, Advanced, Expert', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='interview_count',
            field=models.IntegerField(default=0, help_text='Number of interviews conducted/taken'),
        ),
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Date the employee joined the organization (from ERP)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mentor',
            field=models.ForeignKey(blank=True, help_text='Assigned mentor (FK to another User)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Admin notes about this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='sbu_name',
            field=models.CharField(blank=True, default='', help_text='Strategic Business Unit name from ERP', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='training_level',
            field=models.CharField(blank=True, default='', help_text='Current training level (self-editable)', max_length=50),
        ),
    ]
