from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class TopicKnowledge(models.Model):
    """
    Rich knowledge context for each topic within a specific roadmap.
    Generated by LLM, stored as source of truth for RAG validation pipeline.
    Each roadmap has its own contextualised knowledge (Python in backend ≠ Python in data-science).
    """
    # Identity — unique per roadmap + section + topic combination
    roadmap_id = models.CharField(
        max_length=100, db_index=True,
        help_text="Roadmap slug e.g. 'frontend-developer', 'backend-developer'"
    )
    section_id = models.CharField(
        max_length=200,
        help_text="Section slug e.g. 'react', 'internet'"
    )
    section_name = models.CharField(
        max_length=255,
        help_text="Section display name e.g. 'React', 'Internet'"
    )
    topic_name = models.CharField(
        max_length=255, db_index=True,
        help_text="Topic name e.g. 'Learn React', 'How does the internet work?'"
    )

    # FK to actual Topic model (matched during import, nullable if no matching Topic exists)
    topic = models.ForeignKey(
        'Topic', on_delete=models.SET_NULL, null=True, blank=True,
        related_name='knowledge_entries',
        help_text="FK to actual Topic model if matched during load"
    )

    # Benchmark data
    benchmark_hours = models.DecimalField(max_digits=5, decimal_places=1, default=0)
    difficulty = models.IntegerField(
        default=3,
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )

    # Knowledge content (generated by LLM)
    what_it_is = models.TextField(
        help_text="1-2 sentence description of what this topic covers"
    )
    what_you_will_learn = models.JSONField(
        default=list,
        help_text="List of 'ConceptName — explanation' strings"
    )
    subtopics = models.JSONField(
        default=list,
        help_text="List of subtopic keyword strings for matching"
    )
    validation_keywords = models.JSONField(
        default=list,
        help_text="List of keywords for entry validation matching"
    )

    # Versioning
    version_hash = models.CharField(max_length=32, blank=True, default='')
    version = models.IntegerField(default=1)

    # Meta
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'topic_knowledge'
        unique_together = ['roadmap_id', 'section_id', 'topic_name']
        indexes = [
            models.Index(fields=['roadmap_id', 'topic_name']),
            models.Index(fields=['topic_name']),
        ]
        ordering = ['roadmap_id', 'section_id']
        verbose_name = 'Topic Knowledge'
        verbose_name_plural = 'Topic Knowledge'

    def __str__(self):
        return f"[{self.roadmap_id}] {self.section_name} > {self.topic_name}"


class Topic(models.Model):
    """
    Hierarchical topic model for learning topics.
    Supports parent-child relationships and soft delete.
    """
    name = models.CharField(max_length=255)
    parent = models.ForeignKey(
        'self',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='children'
    )
    depth = models.IntegerField(default=0, help_text="Hierarchy depth (0=root)")
    benchmark_hours = models.DecimalField(
        max_digits=5,
        decimal_places=1,
        default=0,
        help_text="Expected hours to complete this topic"
    )
    difficulty = models.IntegerField(
        default=3,
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        help_text="Difficulty level 1-5"
    )
    is_active = models.BooleanField(
        default=True,
        help_text="Soft delete flag - False means deleted"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    DOMAIN_CHOICES = [
        # --- Core Engineering ---
        ('frontend', 'Frontend'),
        ('backend', 'Backend'),
        ('fullstack', 'Full Stack'),
        ('devops', 'DevOps'),
        ('devsecops', 'DevSecOps'),
        ('mobile', 'Mobile'),
        ('android', 'Android'),
        ('ios', 'iOS'),
        ('game', 'Game Developer'),
        ('game_server', 'Server Side Game Developer'),
        ('qa', 'QA'),
        ('test_automation', 'Test Automation'),
        
        # --- Data & AI ---
        ('data', 'Data Analyst'),
        ('data_engineer', 'Data Engineer'),
        ('ai', 'AI Engineer'),
        ('ai_data_scientist', 'AI and Data Scientist'),
        ('ml', 'Machine Learning'),
        ('mlops', 'MLOps'),
        ('bi', 'BI Analyst'),
        
        # --- specialized ---
        ('blockchain', 'Blockchain'),
        ('cyber_security', 'Cyber Security'),
        ('architect', 'Software Architect'),
        ('db_admin', 'PostgreSQL / DBA'),
        
        # --- Product & Design ---
        ('product_manager', 'Product Manager'),
        ('engineering_manager', 'Engineering Manager'),
        ('design', 'UX Design'),
        ('technical_writer', 'Technical Writer'),
        ('devrel', 'Developer Relations'),
        
        # --- Fallbacks ---
        ('fundamentals', 'Computer Science / Fundamentals'),
        ('soft_skills', 'Soft Skills'),
        ('general', 'General'),
    ]
    domain = models.CharField(
        max_length=20,
        choices=DOMAIN_CHOICES,
        default='general',
        help_text="Domain area for estimation context"
    )
    language = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        help_text="Programming language (e.g. 'python', 'javascript')"
    )

    class Meta:
        unique_together = ['name', 'parent']
        ordering = ['name']
        verbose_name = 'Topic'
        verbose_name_plural = 'Topics'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        """Calculate depth before saving"""
        if self.parent:
            self.depth = self.parent.depth + 1
        else:
            self.depth = 0
        super().save(*args, **kwargs)
        
        # If this topic has children, their depth might need updating
        # (Only relevant if moving a topic, but good for data integrity)
        for child in self.children.all():
            if child.depth != self.depth + 1:
                child.save()

    def soft_delete(self):
        """
        [Reload Triggered]
        Soft delete this topic and all its descendants recursively.
        Also removes this topic from any Training Plans to prevent 'ghost' hours.
        """
        # 1. Recursive soft delete for children
        children = self.children.filter(is_active=True)
        for child in children:
            child.soft_delete()

        # 2. Remove from Training Plans (Hard delete the association, as the topic is effectively gone)
        # We import here to avoid circular imports if any
        from apps.training_plans.models import PlanTopic
        PlanTopic.objects.filter(topic=self).delete()

        # 3. Soft delete self
        self.is_active = False
        self.save()


class LearnerTopicMastery(models.Model):
    """
    Tracks a learner's conceptual progress and mastery status for a topic.
    Supports bidirectional propagation of mastery state.
    """
    user = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        related_name='topic_masteries'
    )
    topic = models.ForeignKey(
        Topic,
        on_delete=models.CASCADE,
        related_name='learner_masteries'
    )
    current_progress = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text="Conceptual completion percentage (0-100%)"
    )
    total_hours = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        default=0,
        help_text="Cumulative hours logged for this topic"
    )
    is_locked = models.BooleanField(
        default=False,
        help_text="Locked if mastered (100%) or via hierarchy propagation"
    )
    last_entry_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'learner_topic_masteries'
        unique_together = ['user', 'topic']
        verbose_name = 'Learner Topic Mastery'
        verbose_name_plural = 'Learner Topic Masteries'

    def __str__(self):
        return f"{self.user.email} - {self.topic.name} ({self.current_progress}%)"

    def update_mastery(self, progress, hours, is_completed, entry_date):
        """
        Update leaf progress and trigger automated parent calculation.
        """
        if is_completed:
            self.current_progress = 100
            self.is_locked = True
        
        self.total_hours += hours
        self.save()
        
        # Propagation Logic
        if self.is_locked:
            self.propagate_down()
        
        # Always propagate up to update parent averages
        self.propagate_up()

    def recalculate_mastery(self, trigger_propagation=True):
        """
        Scan all active entries and children to rebuild mastery state.
        For leaf topics: Uses entry status.
        For parents: Uses child averages.
        """
        from apps.entries.models import Entry
        
        # Check if topic is leaf (no active children)
        children = Topic.objects.filter(parent=self.topic, is_active=True)
        has_children = children.exists()

        if not has_children:
            # Leaf logic: check entries
            entries = Entry.objects.filter(
                user=self.user,
                topic=self.topic,
                is_active=True
            ).order_by('date', 'created_at')

            if not entries.exists():
                self.current_progress = 0
                self.total_hours = 0
                self.is_locked = False
                self.last_entry_at = None
            else:
                self.total_hours = sum(e.hours for e in entries)
                # If any entry is completed, progress is 100%
                if entries.filter(is_completed=True).exists():
                    self.current_progress = 100
                    self.is_locked = True
                else:
                    # v8.0: Binary — if no entry is completed, progress is 0
                    self.current_progress = 0
                    self.is_locked = self.current_progress >= 100
                
                self.last_entry_at = entries.last().created_at
        else:
            # Parent logic: Average of children
            total_calc_progress = 0
            count = children.count()
            
            for child in children:
                child_m, _ = LearnerTopicMastery.objects.get_or_create(
                    user=self.user,
                    topic=child
                )
                # Force a refresh of the child's organic state before calculating parent average
                # This breaks the "Lock Trap" where children stay at 100% because they were forced previously.
                child_m.recalculate_mastery(trigger_propagation=False)
                total_calc_progress += child_m.current_progress

            # Check for direct completion on the parent
            direct_entries = Entry.objects.filter(user=self.user, topic=self.topic, is_active=True)
            parent_is_directly_completed = direct_entries.filter(is_completed=True).exists()

            if parent_is_directly_completed:
                self.current_progress = 100
                self.is_locked = True
            else:
                self.current_progress = total_calc_progress / count if count > 0 else 0
                
                # Parent is locked only if ALL children are 100% AND locked
                all_children_locked = True
                for child in children:
                    child_m, _ = LearnerTopicMastery.objects.get_or_create(user=self.user, topic=child)
                    if not child_m.is_locked or child_m.current_progress < 100:
                        all_children_locked = False
                        break
                
                self.is_locked = all_children_locked
            
            child_hours = sum(
                LearnerTopicMastery.objects.filter(user=self.user, topic__in=children).values_list('total_hours', flat=True)
            )
            self.total_hours = sum(e.hours for e in direct_entries) + child_hours
            
            if direct_entries.exists():
                self.last_entry_at = direct_entries.order_by('-created_at').first().created_at

        self.save()
        
        if trigger_propagation:
            self.propagate_up()
            if self.is_locked:
                self.propagate_down()

    def propagate_down(self):
        """
        Parent mastered -> All descendants mastered.
        Parent unlocked -> Trigger recalculation for all descendants to revert to organic state.
        """
        children = Topic.objects.filter(parent=self.topic, is_active=True)
        for child in children:
            child_mastery, _ = LearnerTopicMastery.objects.get_or_create(
                user=self.user,
                topic=child
            )
            
            if self.is_locked:
                # Parent is locked -> Force child to 100%
                if not child_mastery.is_locked:
                    child_mastery.current_progress = 100
                    child_mastery.is_locked = True
                    child_mastery.save()
                    child_mastery.propagate_down()
            else:
                # Parent is UNLOCKED -> Child must check its own "organic" state
                # If it was only 100% because of this parent, it will now drop/unlock.
                if child_mastery.is_locked:
                    # trigger_propagation=False to prevent circular upward calls
                    child_mastery.recalculate_mastery(trigger_propagation=False)
                    child_mastery.propagate_down()

    def propagate_up(self):
        """
        Update parent's progress based on children averages.
        """
        if not self.topic.parent:
            return

        parent = self.topic.parent
        siblings = Topic.objects.filter(parent=parent, is_active=True)
        sibling_count = siblings.count()
        
        if sibling_count == 0:
            return

        total_progress = 0
        all_mastered = True
        
        for sibling in siblings:
            sibling_mastery, _ = LearnerTopicMastery.objects.get_or_create(
                user=self.user,
                topic=sibling
            )
            total_progress += sibling_mastery.current_progress
            if not sibling_mastery.is_locked or sibling_mastery.current_progress < 100:
                all_mastered = False
        
        parent_mastery, _ = LearnerTopicMastery.objects.get_or_create(
            user=self.user,
            topic=parent
        )
        
        parent_mastery.current_progress = total_progress / sibling_count
        parent_mastery.is_locked = all_mastered
        parent_mastery.save()
        
        # Continue up
        parent_mastery.propagate_up()


class TopicResource(models.Model):
    """
    YouTube video resources linked to a topic.
    Generated via YouTube Data API or manually added by admin.
    Fetched on-demand when user/admin expands a topic — NOT on page load.
    """
    topic = models.ForeignKey(
        Topic,
        on_delete=models.CASCADE,
        related_name='resources',
    )
    title = models.CharField(max_length=500)
    url = models.URLField(max_length=500)
    youtube_video_id = models.CharField(
        max_length=20, blank=True, default='',
        help_text="YouTube video ID extracted from URL",
    )
    channel_name = models.CharField(max_length=255, blank=True, default='')
    duration_minutes = models.IntegerField(
        default=0,
        help_text="Video duration in minutes",
    )
    view_count = models.IntegerField(default=0)
    like_count = models.IntegerField(default=0)
    thumbnail_url = models.URLField(max_length=500, blank=True, default='')
    description = models.TextField(blank=True, default='')

    GENERATED_BY_CHOICES = [
        ('ai', 'AI / YouTube API'),
        ('admin', 'Admin Added'),
    ]
    generated_by = models.CharField(
        max_length=10,
        choices=GENERATED_BY_CHOICES,
        default='ai',
    )

    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'topic_resources'
        ordering = ['-view_count']
        unique_together = ['topic', 'youtube_video_id']
        verbose_name = 'Topic Resource'
        verbose_name_plural = 'Topic Resources'

    def __str__(self):
        return f"{self.topic.name} — {self.title[:60]}"

