# Generated by Django 4.2.9 on 2026-01-28 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='True = Active (available for assignment), False = Draft')),
                ('is_archived', models.BooleanField(default=False, help_text='Soft delete flag - True means archived')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training Plan',
                'verbose_name_plural': 'Training Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(default=1)),
                ('expected_hours', models.DecimalField(decimal_places=1, help_text='Custom hours for this topic in this plan', max_digits=5)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_topics', to='training_plans.trainingplan')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_topics', to='topics.topic')),
            ],
            options={
                'verbose_name': 'Plan Topic',
                'verbose_name_plural': 'Plan Topics',
                'ordering': ['sequence_order'],
                'unique_together': {('plan', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='PlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='training_plans.trainingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Assignment',
                'verbose_name_plural': 'Plan Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('plan', 'user')},
            },
        ),
    ]
