# Generated by Django 4.2.9 on 2026-01-29 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_depth_alter_topic_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='plan_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plantopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='plan_topics', to='topics.topic'),
        ),
    ]
