# Generated by Django 4.2.9 on 2026-02-13 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_learnertopicmastery'),
        ('training_plans', '0002_alter_planassignment_user_alter_plantopic_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantopic',
            name='node_type',
            field=models.CharField(choices=[('topic', 'Topic'), ('section', 'Section Header')], default='topic', help_text='Type of node in the roadmap graph', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='source_template',
            field=models.CharField(blank=True, help_text='ID of the roadmap template this plan was created from', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='target_role',
            field=models.CharField(blank=True, help_text='Target role (e.g., Frontend Developer)', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PlanTopicEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='training_plans.trainingplan')),
                ('source_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='topics.topic')),
                ('target_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='topics.topic')),
            ],
            options={
                'verbose_name': 'Plan Topic Edge',
                'verbose_name_plural': 'Plan Topic Edges',
                'unique_together': {('plan', 'source_topic', 'target_topic')},
            },
        ),
    ]
