# Generated by Django 4.2.9 on 2026-04-24 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0010_topicresource'),
        ('training_plans', '0003_add_roadmap_fields_and_edge_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantopic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='plantopic',
            name='lms_course_id',
            field=models.IntegerField(blank=True, help_text="Moodle course ID (only for source='lms')", null=True),
        ),
        migrations.AddField(
            model_name='plantopic',
            name='lms_course_name',
            field=models.CharField(blank=True, default='', help_text='Cached LMS course name for display', max_length=500),
        ),
        migrations.AddField(
            model_name='plantopic',
            name='source',
            field=models.CharField(choices=[('curated', 'Curated Roadmap Topic'), ('lms', 'LMS Course (Moodle)')], default='curated', help_text='Where this plan item came from', max_length=10),
        ),
        migrations.AlterField(
            model_name='plantopic',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='ALTS topic (required for curated, null for LMS courses)', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='plan_topics', to='topics.topic'),
        ),
    ]
