# Generated by Django 4.2.9 on 2026-02-02 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Action performed (e.g., 'create_entry')", max_length=50)),
                ('entity_type', models.CharField(help_text="Type of entity affected (e.g., 'entry')", max_length=50)),
                ('entity_id', models.IntegerField(help_text='ID of the affected entity')),
                ('before_state', models.JSONField(blank=True, help_text='Snapshot before change', null=True)),
                ('after_state', models.JSONField(blank=True, help_text='Snapshot after change', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the action (e.g., override reason)', null=True)),
                ('comment', models.TextField(blank=True, help_text='Additional comments', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(help_text='The user affected by an admin action (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user (Actor) who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['created_at'], name='audit_logs_created_262184_idx')],
            },
        ),
    ]
