# Generated by Django 4.2.9 on 2026-02-03 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Action performed (e.g., 'create_entry')", max_length=50)),
                ('entity_type', models.CharField(help_text='Type of entity affected', max_length=50)),
                ('entity_id', models.CharField(help_text='ID of the affected entity', max_length=255)),
                ('status', models.CharField(default='SUCCESS', help_text='Status of the action', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(help_text='The user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx')],
            },
        ),
    ]
