# Generated by Django 4.2.9 on 2026-02-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='after_state',
            field=models.JSONField(blank=True, help_text='State after the action', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='before_state',
            field=models.JSONField(blank=True, help_text='State before the action', null=True),
        ),
    ]
