# Generated by Django 4.2.9 on 2026-04-24 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training_plans', '0003_add_roadmap_fields_and_edge_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('pm_approved', 'PM Approved'), ('pm_rejected', 'PM Rejected'), ('lnd_approved', 'LND Approved'), ('lnd_rejected', 'LND Rejected'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('initiated_by', models.CharField(choices=[('user', 'User Request'), ('admin', 'Admin Assignment')], default='user', max_length=10)),
                ('request_reason', models.TextField(blank=True, default='', help_text='Why the user wants this plan (user-initiated requests)', max_length=500)),
                ('pm_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('pm_notes', models.TextField(blank=True, default='', max_length=500)),
                ('lnd_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('lnd_notes', models.TextField(blank=True, default='', max_length=500)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lnd_reviewer', models.ForeignKey(blank=True, help_text='L&D Admin who gave final approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lnd_reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(help_text='Training plan being requested', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='training_plans.trainingplan')),
                ('pm_reviewer', models.ForeignKey(blank=True, help_text='Project Manager who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Learner requesting or being assigned the plan', on_delete=django.db.models.deletion.CASCADE, related_name='plan_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Plan Request',
                'verbose_name_plural': 'Training Plan Requests',
                'db_table': 'training_plan_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='trainingplanrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'pm_approved', 'active'])), fields=('user', 'plan'), name='unique_active_plan_request'),
        ),
    ]
