# Generated by Django 4.2.9 on 2026-03-31 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], help_text='Report period type', max_length=20)),
                ('period_start', models.DateField(help_text='Start date of the report period')),
                ('period_end', models.DateField(help_text='End date of the report period')),
                ('markdown_content', models.TextField(default='', help_text='AI-generated markdown report with insights and recommendations')),
                ('charts_data', models.JSONField(default=dict, help_text='Structured data for frontend Recharts components')),
                ('raw_stats', models.JSONField(default=dict, help_text='Raw aggregated stats used to generate the report')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When this report was generated')),
                ('generation_time_seconds', models.FloatField(default=0, help_text='How long the generation took (including AI call)')),
                ('ai_model', models.CharField(default='qwen2.5:7b', help_text='Which LLM generated the insights', max_length=50)),
                ('user', models.ForeignKey(help_text='User this report is generated for', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', 'period', '-generated_at'], name='idx_report_user_period')],
            },
        ),
    ]
