"""add_total_classes_offered_to_courses

Revision ID: 042226f406cc
Revises: fc8b96f4698b
Create Date: 2025-11-11 15:26:23.795449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042226f406cc'
down_revision = 'fc8b96f4698b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('total_classes_offered', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'total_classes_offered')
    # ### end Alembic commands ###

