"""add_lms_cache_tables

Revision ID: 1ff0728b4682
Revises: e0771c4e76d4
Create Date: 2025-11-24 18:53:42.523663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ff0728b4682'
down_revision = 'e0771c4e76d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lms_category_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_category_cache_id'), 'lms_category_cache', ['id'], unique=False)
    op.create_table('lms_course_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('shortname', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('startdate', sa.Integer(), nullable=True),
    sa.Column('enddate', sa.Integer(), nullable=True),
    sa.Column('categoryid', sa.Integer(), nullable=True),
    sa.Column('categoryname', sa.String(), nullable=True),
    sa.Column('visible', sa.Integer(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lms_course_cache_cached_at', 'lms_course_cache', ['cached_at'], unique=False)
    op.create_index(op.f('ix_lms_course_cache_id'), 'lms_course_cache', ['id'], unique=False)
    op.create_table('lms_course_enrollment_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_data', sa.JSON(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lms_enrollment_cache_cached_at', 'lms_course_enrollment_cache', ['cached_at'], unique=False)
    op.create_index('idx_lms_enrollment_cache_course_id', 'lms_course_enrollment_cache', ['course_id'], unique=False)
    op.create_index(op.f('ix_lms_course_enrollment_cache_course_id'), 'lms_course_enrollment_cache', ['course_id'], unique=False)
    op.create_table('lms_user_course_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('course_data', sa.JSON(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lms_user_course_cache_cached_at', 'lms_user_course_cache', ['cached_at'], unique=False)
    op.create_index('idx_lms_user_course_cache_username', 'lms_user_course_cache', ['username'], unique=False)
    op.create_index(op.f('ix_lms_user_course_cache_username'), 'lms_user_course_cache', ['username'], unique=False)
    op.drop_index('ix_class_reminders_class_date', table_name='class_reminders')
    op.drop_index('ix_class_reminders_course_id', table_name='class_reminders')
    op.drop_index('ix_class_reminders_id', table_name='class_reminders')
    op.drop_table('class_reminders')
    op.drop_constraint('course_comments_course_id_fkey', 'course_comments', type_='foreignkey')
    op.create_foreign_key(None, 'course_comments', 'courses', ['course_id'], ['id'])
    op.drop_constraint('uq_course_draft_course_id', 'course_drafts', type_='unique')
    op.drop_constraint('course_drafts_course_id_fkey', 'course_drafts', type_='foreignkey')
    op.create_foreign_key(None, 'course_drafts', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_drafts', type_='foreignkey')
    op.create_foreign_key('course_drafts_course_id_fkey', 'course_drafts', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_course_draft_course_id', 'course_drafts', ['course_id'])
    op.drop_constraint(None, 'course_comments', type_='foreignkey')
    op.create_foreign_key('course_comments_course_id_fkey', 'course_comments', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_table('class_reminders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('batch_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('class_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('day', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reminder_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('sent', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='class_reminders_pkey'),
    sa.UniqueConstraint('course_id', 'class_date', 'start_time', name='uq_class_reminder')
    )
    op.create_index('ix_class_reminders_id', 'class_reminders', ['id'], unique=False)
    op.create_index('ix_class_reminders_course_id', 'class_reminders', ['course_id'], unique=False)
    op.create_index('ix_class_reminders_class_date', 'class_reminders', ['class_date'], unique=False)
    op.drop_index(op.f('ix_lms_user_course_cache_username'), table_name='lms_user_course_cache')
    op.drop_index('idx_lms_user_course_cache_username', table_name='lms_user_course_cache')
    op.drop_index('idx_lms_user_course_cache_cached_at', table_name='lms_user_course_cache')
    op.drop_table('lms_user_course_cache')
    op.drop_index(op.f('ix_lms_course_enrollment_cache_course_id'), table_name='lms_course_enrollment_cache')
    op.drop_index('idx_lms_enrollment_cache_course_id', table_name='lms_course_enrollment_cache')
    op.drop_index('idx_lms_enrollment_cache_cached_at', table_name='lms_course_enrollment_cache')
    op.drop_table('lms_course_enrollment_cache')
    op.drop_index(op.f('ix_lms_course_cache_id'), table_name='lms_course_cache')
    op.drop_index('idx_lms_course_cache_cached_at', table_name='lms_course_cache')
    op.drop_table('lms_course_cache')
    op.drop_index(op.f('ix_lms_category_cache_id'), table_name='lms_category_cache')
    op.drop_table('lms_category_cache')
    # ### end Alembic commands ###

