"""add_lms_user_cache

Revision ID: 292e3a096c53
Revises: 1ff0728b4682
Create Date: 2025-11-24 18:57:46.495701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292e3a096c53'
down_revision = '1ff0728b4682'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lms_user_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_data', sa.JSON(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lms_user_cache_cached_at', 'lms_user_cache', ['cached_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lms_user_cache_cached_at', table_name='lms_user_cache')
    op.drop_table('lms_user_cache')
    # ### end Alembic commands ###

