"""add_lms_users_table

Revision ID: 2cc323888506
Revises: a4743fd9e159
Create Date: 2025-11-26 16:31:14.700952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc323888506'
down_revision = 'a4743fd9e159'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lms_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lms_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('firstaccess', sa.BigInteger(), nullable=True),
    sa.Column('lastaccess', sa.BigInteger(), nullable=True),
    sa.Column('auth', sa.String(), nullable=True),
    sa.Column('suspended', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('mailformat', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('descriptionformat', sa.Integer(), nullable=True),
    sa.Column('profileimageurlsmall', sa.String(), nullable=True),
    sa.Column('profileimageurl', sa.String(), nullable=True),
    sa.Column('customfields', sa.JSON(), nullable=True),
    sa.Column('lms_data', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lms_user_email', 'lms_users', ['email'], unique=False)
    op.create_index('idx_lms_user_lms_id', 'lms_users', ['lms_id'], unique=False)
    op.create_index('idx_lms_user_username', 'lms_users', ['username'], unique=False)
    op.create_index(op.f('ix_lms_users_email'), 'lms_users', ['email'], unique=False)
    op.create_index(op.f('ix_lms_users_lms_id'), 'lms_users', ['lms_id'], unique=True)
    op.create_index(op.f('ix_lms_users_username'), 'lms_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lms_users_username'), table_name='lms_users')
    op.drop_index(op.f('ix_lms_users_lms_id'), table_name='lms_users')
    op.drop_index(op.f('ix_lms_users_email'), table_name='lms_users')
    op.drop_index('idx_lms_user_username', table_name='lms_users')
    op.drop_index('idx_lms_user_lms_id', table_name='lms_users')
    op.drop_index('idx_lms_user_email', table_name='lms_users')
    op.drop_table('lms_users')
    # ### end Alembic commands ###

