"""add_course_name_batch_code_to_enrollments_preserve_history

Revision ID: 6e36db3a7375
Revises: 042226f406cc
Create Date: 2025-11-11 16:42:50.989138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e36db3a7375'
down_revision = '042226f406cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('course_name', sa.String(), nullable=True))
    op.add_column('enrollments', sa.Column('batch_code', sa.String(), nullable=True))
    op.alter_column('enrollments', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollments', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('enrollments', 'batch_code')
    op.drop_column('enrollments', 'course_name')
    # ### end Alembic commands ###

