"""add_erp_employee_cache

Revision ID: 7c4e48eb5dfd
Revises: 292e3a096c53
Create Date: 2025-11-25 17:05:29.152894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4e48eb5dfd'
down_revision = '292e3a096c53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_employee_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_data', sa.JSON(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_erp_employee_cache_cached_at', 'erp_employee_cache', ['cached_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_erp_employee_cache_cached_at', table_name='erp_employee_cache')
    op.drop_table('erp_employee_cache')
    # ### end Alembic commands ###

