"""add_timecreated_to_lms_course_cache

Revision ID: 97e336a3edca
Revises: add_enrollment_time
Create Date: 2025-11-30 19:55:55.919401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e336a3edca'
down_revision = 'add_enrollment_time'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lms_course_cache', sa.Column('timecreated', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lms_user_courses_employee_id'), 'lms_user_courses', ['employee_id'], unique=False)
    op.create_index(op.f('ix_lms_user_courses_lms_course_id'), 'lms_user_courses', ['lms_course_id'], unique=False)
    op.create_index(op.f('ix_lms_user_courses_student_id'), 'lms_user_courses', ['student_id'], unique=False)
    op.drop_index('idx_students_is_mentor', table_name='students')
    op.create_index(op.f('ix_students_is_mentor'), 'students', ['is_mentor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_is_mentor'), table_name='students')
    op.create_index('idx_students_is_mentor', 'students', ['is_mentor'], unique=False)
    op.drop_index(op.f('ix_lms_user_courses_student_id'), table_name='lms_user_courses')
    op.drop_index(op.f('ix_lms_user_courses_lms_course_id'), table_name='lms_user_courses')
    op.drop_index(op.f('ix_lms_user_courses_employee_id'), table_name='lms_user_courses')
    op.drop_column('lms_course_cache', 'timecreated')
    # ### end Alembic commands ###

