"""add_course_type_location_cost_to_courses

Revision ID: d3c878a66f88
Revises: 97e336a3edca
Create Date: 2025-11-30 20:22:42.688239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c878a66f88'
down_revision = '97e336a3edca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add course_type as nullable first
    op.add_column('courses', sa.Column('course_type', sa.String(), nullable=True))
    # Set default value for existing courses (assume they're onsite)
    op.execute("UPDATE courses SET course_type = 'onsite' WHERE course_type IS NULL")
    # Now make it NOT NULL
    op.alter_column('courses', 'course_type', nullable=False, server_default='onsite')
    # Add location and cost columns
    op.add_column('courses', sa.Column('location', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # Create index
    op.create_index(op.f('ix_courses_course_type'), 'courses', ['course_type'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_course_type'), table_name='courses')
    op.drop_column('courses', 'cost')
    op.drop_column('courses', 'location')
    op.drop_column('courses', 'course_type')
    # ### end Alembic commands ###

