"""add_attendance_fields_to_enrollments

Revision ID: fc8b96f4698b
Revises: 001
Create Date: 2025-11-10 17:39:47.476148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8b96f4698b'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('total_attendance', sa.Integer(), nullable=True))
    op.add_column('enrollments', sa.Column('present', sa.Integer(), nullable=True))
    op.add_column('enrollments', sa.Column('attendance_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'attendance_status')
    op.drop_column('enrollments', 'present')
    op.drop_column('enrollments', 'total_attendance')
    # ### end Alembic commands ###

