# Generated by Django 4.2.9 on 2026-01-29 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='depth',
            field=models.IntegerField(default=0, help_text='Hierarchy depth (0=root)'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='topics.topic'),
        ),
    ]
