# Generated by Django 4.2.27 on 2026-01-29 08:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0002_topic_depth_alter_topic_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerTopicMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.DecimalField(decimal_places=2, default=0, help_text='Conceptual completion percentage (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, help_text='Cumulative hours logged for this topic', max_digits=7)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked if mastered (100%) or via hierarchy propagation')),
                ('last_entry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_masteries', to='topics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_masteries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learner Topic Mastery',
                'verbose_name_plural': 'Learner Topic Masteries',
                'db_table': 'learner_topic_masteries',
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
