# Generated by Django 4.2.9 on 2026-02-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_learnertopicmastery'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'parent')},
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topics',
        ),
    ]
