# Generated by Django 4.2.9 on 2026-02-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_alter_topic_unique_together_alter_topic_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table=None,
        ),
    ]
