# Generated by Django 4.2.9 on 2026-02-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_alter_topic_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='domain',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('devops', 'DevOps'), ('mobile', 'Mobile'), ('data', 'Data'), ('qa', 'QA'), ('general', 'General')], default='general', help_text='Domain area for estimation context', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='language',
            field=models.CharField(blank=True, help_text="Programming language (e.g. 'python', 'javascript')", max_length=50, null=True),
        ),
    ]
