# Generated by Django 4.2.9 on 2026-02-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_topic_domain_topic_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='domain',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('fullstack', 'Full Stack'), ('devops', 'DevOps'), ('devsecops', 'DevSecOps'), ('mobile', 'Mobile'), ('data', 'Data'), ('ai', 'AI/ML'), ('game', 'Game Dev'), ('qa', 'QA'), ('security', 'Cyber Security'), ('product', 'Product'), ('design', 'Design'), ('general', 'General')], default='general', help_text='Domain area for estimation context', max_length=20),
        ),
    ]
