# Generated by Django 4.2.9 on 2026-02-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_alter_topic_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='domain',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Full Stack'), ('devops', 'DevOps'), ('devsecops', 'DevSecOps'), ('mobile', 'Mobile'), ('android', 'Android'), ('ios', 'iOS'), ('game', 'Game Developer'), ('game_server', 'Server Side Game Developer'), ('qa', 'QA'), ('test_automation', 'Test Automation'), ('data', 'Data Analyst'), ('data_engineer', 'Data Engineer'), ('ai', 'AI Engineer'), ('ai_data_scientist', 'AI and Data Scientist'), ('ml', 'Machine Learning'), ('mlops', 'MLOps'), ('bi', 'BI Analyst'), ('blockchain', 'Blockchain'), ('cyber_security', 'Cyber Security'), ('architect', 'Software Architect'), ('db_admin', 'PostgreSQL / DBA'), ('product_manager', 'Product Manager'), ('engineering_manager', 'Engineering Manager'), ('design', 'UX Design'), ('technical_writer', 'Technical Writer'), ('devrel', 'Developer Relations'), ('fundamentals', 'Computer Science / Fundamentals'), ('soft_skills', 'Soft Skills'), ('general', 'General')], default='general', help_text='Domain area for estimation context', max_length=20),
        ),
    ]
