# Generated by Django 4.2.9 on 2026-02-23 07:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_alter_topic_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadmap_id', models.CharField(db_index=True, help_text="Roadmap slug e.g. 'frontend-developer', 'backend-developer'", max_length=100)),
                ('section_id', models.CharField(help_text="Section slug e.g. 'react', 'internet'", max_length=200)),
                ('section_name', models.CharField(help_text="Section display name e.g. 'React', 'Internet'", max_length=255)),
                ('topic_name', models.CharField(db_index=True, help_text="Topic name e.g. 'Learn React', 'How does the internet work?'", max_length=255)),
                ('benchmark_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('difficulty', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('what_it_is', models.TextField(help_text='1-2 sentence description of what this topic covers')),
                ('what_you_will_learn', models.JSONField(default=list, help_text="List of 'ConceptName — explanation' strings")),
                ('subtopics', models.JSONField(default=list, help_text='List of subtopic keyword strings for matching')),
                ('validation_keywords', models.JSONField(default=list, help_text='List of keywords for entry validation matching')),
                ('version_hash', models.CharField(blank=True, default='', max_length=32)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(blank=True, help_text='FK to actual Topic model if matched during load', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries', to='topics.topic')),
            ],
            options={
                'verbose_name': 'Topic Knowledge',
                'verbose_name_plural': 'Topic Knowledge',
                'db_table': 'topic_knowledge',
                'ordering': ['roadmap_id', 'section_id'],
                'indexes': [models.Index(fields=['roadmap_id', 'topic_name'], name='topic_knowl_roadmap_d020fa_idx'), models.Index(fields=['topic_name'], name='topic_knowl_topic_n_646e8a_idx')],
                'unique_together': {('roadmap_id', 'section_id', 'topic_name')},
            },
        ),
    ]
