# Generated by Django 4.2.9 on 2026-04-03 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_topicknowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('youtube_video_id', models.CharField(blank=True, default='', help_text='YouTube video ID extracted from URL', max_length=20)),
                ('channel_name', models.CharField(blank=True, default='', max_length=255)),
                ('duration_minutes', models.IntegerField(default=0, help_text='Video duration in minutes')),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('generated_by', models.CharField(choices=[('ai', 'AI / YouTube API'), ('admin', 'Admin Added')], default='ai', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='topics.topic')),
            ],
            options={
                'verbose_name': 'Topic Resource',
                'verbose_name_plural': 'Topic Resources',
                'db_table': 'topic_resources',
                'ordering': ['-view_count'],
                'unique_together': {('topic', 'youtube_video_id')},
            },
        ),
    ]
